version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: Active@53
      MYSQL_DATABASE: testdb 
      MYSQL_PORT: 3306

  redis:
    image: redis:7-alpine

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Active@53
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5